New Problem: Descriptive Statistics (#136)
Open-Deep-ML/DML-OpenProblem pull request #175
Opened 2024-11-15 09:59 UTC by BhardwajArjit

2024-12-19 15:06 UTC, moe18 requested changes
one small request, but looks good overall

2024-12-19 15:06 UTC, moe18 commented on Problems/77_descriptive_stats/learn.html
> +    25\% \text{ Percentile} = 13.5, \quad 75\% \text{ Percentile} = 17.5
I would add the 50% percentile, while I know it is the same as the median I think it might be confusing to someone just staring out

2024-12-28 09:07 UTC, BhardwajArjit commented
Hi @moe18, I have added the 50% percentile in the html file. I saw another problem with the same number i.e. 77, so please let me know to what number I should update this problem statement's number.

2025-01-20 14:44 UTC, moe18 commented
could you make this question 78

2025-01-20 16:54 UTC, BhardwajArjit commented
there is another question with the number 78. There is no question with 79, so I'll make it 79. Is it okay?

2025-02-03 23:23 UTC, moe18 commented
make it 78 so that it is the same as on the website, I will need to change whatever is 78 on the repo

2025-02-05 07:51 UTC, BhardwajArjit commented
Hey @moe18, I have changed the problem number to 78.

2025-02-05 13:17 UTC, moe18 approved these changes

2025-02-05 13:17 UTC, merged